// Copyright 2024 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image -i noto_sans_24.png -f mono16`

#pragma once

#include <qp.h>

extern const uint32_t font_noto_sans_24_length;
extern const uint8_t  font_noto_sans_24[9757];
