BOARD = GENERIC_RP_RP2040
SERIAL_DRIVER = vendor
#SRC += tinyexpr.c
#DIP_SWITCH_ENABLE = yes
QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += ssd1322_spi
SRC += noto_sans_24.qff.c
SRC += tinyexpr.c
